apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: REPLACE_FRONTEND_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_BASE_URL
              value: http://backend.fullstack.svc.cluster.local:8000
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 10
            periodSeconds: 20
      imagePullSecrets:
        - name: acr-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fullstack
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 5173
      protocol: TCP
      name: http
